research_task:
  description: >
    Your task is to download JSON data from the provided website URL: {website_url} using the JSONDownloader tool.
    You must use this URL and not any other.
    Then, analyze the JSON data to identify any deprecated dependencies or security vulnerabilities.
    Use any other tools available to assist in your analysis.
  expected_output: >
    A detailed report summarizing the findings from the JSON data analysis.
  agent: researcher

reporting_task:
  description: >
    Generate a detailed report based on the analysis, listing each dependency with its deprecation and security status.
    The report should:
    - Clearly present the findings from the analysis.
    - Be formatted for readability.
  expected_output: >
    A comprehensive report listing each dependency, its version, deprecation status, and security status.
  agent: reporting_analyst