research_task:
  description: >
    Your task is to download the dependency manager file from the provided URL: {dependency_file_url} using the DependencyFileDownloader tool.
    You must use this URL and not any other.
    Then, analyze the file to identify any deprecated dependencies or known security vulnerabilities.
    Use the tools available to assist in your analysis.
  expected_output: >
    A detailed report summarizing any deprecated dependencies and security vulnerabilities found in the dependency file.
  agent: researcher

reporting_task:
  description: >
    Generate a detailed report based on the analysis, listing each dependency with its deprecation and security status.
    The report should:
    - Clearly present the findings from the analysis.
    - Be formatted for readability.
  expected_output: >
    A comprehensive report listing each dependency, its version, deprecation status, and security status.
  agent: reporting_analyst