research_task:
  description: >
    Analyze the PHP file located at {topic} to determine if it has any deprecated dependencies.
    Use Packagist.org as the source of truth to verify the deprecation status of each dependency.
    The task involves:
    - Extracting dependencies from the provided `composer.json` file.
    - Querying Packagist to identify if any listed dependencies are marked as deprecated.
    The focus is solely on identifying whether deprecated dependencies exist, without further recommendations or implementation details.
  expected_output: >
    A simple boolean response: true if any deprecated dependencies are detected, false otherwise.
  agent: researcher

reporting_task:
  description: >
    Generate a detailed report listing the dependencies from the PHP file at {topic}, specifically highlighting any that are deprecated.
    The report should:
    - Provide a list of dependencies from the `composer.json` file.
    - Clearly mark each dependency as either deprecated or not deprecated based on Packagist.org metadata.
    This task focuses solely on presenting the deprecation status for each dependency.
  expected_output: >
    A list of dependencies with their deprecation status: "Deprecated" or "Not Deprecated."
  agent: reporting_analyst
